In [1]:
import numpy as np

In [ ]:
What Happens when we do this?

In [4]:
nums = [1, 2, 3]
nums + [4]

[1, 2, 3, 4]

## Broadcasting across a One Dimentional Array

In [13]:
a = np.array([1, 2, 3])
print(a)
b = 2
print(b)
c = a *b
print(c)

SyntaxError: invalid syntax (<ipython-input-13-4684dd00e534>, line 5)

## Broadcasting across a Two Dimentional Array

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = 2
print(b)
c = a + b
print(c)

[[1 2 3]
 [4 5 6]]
2
[[3 4 5]
 [6 7 8]]


## 1D Array + 2D Array

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = np.array([7, 8, 9])
print(b)
c = a + b
print(c)

[[1 2 3]
 [4 5 6]]
[7 8 9]
[[ 8 10 12]
 [11 13 15]]


## What happeens when the Shapes are not the same?

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = np.array([7, 8, 9, 10])
print(b)
c = a + b
print(c)

[[1 2 3]
 [4 5 6]]
[ 7  8  9 10]


ValueError: operands could not be broadcast together with shapes (2,3) (4,) 